var app = {};
app.INVENTORY = 'listInventory';
app.LIST = 'listShelf';
app.CART = 'listCart';
app.KEY_INVENTORY = 'inventory';
app.KEY_LIST = 'list';
app.KEY_CART = 'cart';
app.DATA_CHANGED_EVENT = 'dataChanged';
app.START_ON = app.INVENTORY;